### ISSUE TITLE
TURBOGRAFX16 CD-ROM

### ISSUE THREAD

**Issue by delgrom** [ZXMicroJack/mist-firmware-rp2040#15]
This core is not loading CDs. Once we have the CD bios loaded and we have mounted a CD image, when the game starts loading it blocks.

Sources of the neptUNOplus port from mist/sidi: https://github.com/delgrom/TurboGrafx16_FPGA/tree/master/neptUNOplus

Thanks.

**Comment by ZXMicroJack** [comment]
Fixed in release v9, please confirm, then I'll close it.
